const players = [
  {
    id: 1,
    name: 'BODYAO',
    games: 36,
    wins: 17,
    loses: 19,
    goalsScored: 132,
    goalsMissed: 144,
    lastGames: [1, 1, 1, 0, 0],
    photo: 'https://i.ibb.co/c3PGPRZ/bodya.png',
  },
  {
    id: 2,
    name: 'TARASYAO',
    games: 25,
    wins: 14,
    loses: 9,
    goalsScored: 107,
    goalsMissed: 98,
    lastGames: [0, 0, 1, 1, 1],
    photo: 'https://i.ibb.co/yd9VTs7/taras.png',
  },
  {
    id: 3,
    name: 'MIKHYAO',
    games: 11,
    wins: 7,
    loses: 4,
    goalsScored: 51,
    goalsMissed: 40,
    lastGames: [1, 1, 0, 1, 0],
    photo: 'https://i.ibb.co/y56GnY7/mike.png',
  },
  {
    id: 4,
    name: 'EUGENYAO',
    games: 18,
    wins: 6,
    loses: 12,
    goalsScored: 66,
    goalsMissed: 62,
    lastGames: [0, 0, 0, 0, 0],
    photo: 'https://i.ibb.co/JvVFCM6/did.png',
  },
  {
    id: 5,
    name: 'NIKITYAO',
    games: 0,
    wins: 0,
    loses: 0,
    goalsScored: 0,
    goalsMissed: 0,

    lastGames: [0, 0, 0, 0, 0],
    photo: 'https://i.ibb.co/Z1Mrf60/nik.png',
  },
  {
    id: 6,
    name: 'IVANYAO',
    games: 0,
    wins: 0,
    loses: 0,
    goalsScored: 0,
    goalsMissed: 0,
    lastGames: [0, 0, 0, 0, 0],
    photo: 'https://i.ibb.co/xMbjdx2/vania.png',
  },
];

export default players;
