const players = [
  {
    id: 1,
    name: 'BODYAO',
    games: 33,
    wins: 17,
    loses: 16,
    goalsScored: 122,
    goalsMissed: 129,
    goalsPerGame: 0,
  },
  {
    id: 2,
    name: 'TARASYAO',
    games: 22,
    wins: 13,
    loses: 9,
    goalsScored: 93,
    goalsMissed: 89,
    goalsPerGame: 0,
  },

  {
    id: 3,
    name: 'MIKHYAO',
    games: 9,
    wins: 6,
    loses: 3,
    goalsScored: 45,
    goalsMissed: 34,
    goalsPerGame: 0,
  },
  {
    id: 4,
    name: 'EUGENYAO',
    games: 18,
    wins: 6,
    loses: 12,
    goalsScored: 66,
    goalsMissed: 62,
    goalsPerGame: 0,
  },
  {
    id: 5,
    name: 'NIKITYAO',
    games: 0,
    wins: 0,
    loses: 0,
    goalsScored: 0,
    goalsMissed: 0,
    goalsPerGame: 0,
  },
  {
    id: 6,
    name: 'IVANYAO',
    games: 0,
    wins: 0,
    loses: 0,
    goalsScored: 0,
    goalsMissed: 0,
    goalsPerGame: 0,
  },
];

export default players;
