const players = [
  {
    id: 1,
    name: 'BODYAO',
    games: 35,
    wins: 17,
    loses: 18,
    goalsScored: 129,
    goalsMissed: 139,
    lastGames: [1, 1, 1, 0, 0],
  },
  {
    id: 2,
    name: 'TARASYAO',
    games: 24,
    wins: 13,
    loses: 9,
    goalsScored: 103,
    goalsMissed: 94,
    lastGames: [0, 0, 1, 1, 1],
  },

  {
    id: 3,
    name: 'MIKHYAO',
    games: 11,
    wins: 7,
    loses: 4,
    goalsScored: 51,
    goalsMissed: 40,
    lastGames: [1, 1, 0, 1, 0],
  },
  {
    id: 4,
    name: 'EUGENYAO',
    games: 18,
    wins: 6,
    loses: 12,
    goalsScored: 66,
    goalsMissed: 62,
    lastGames: [0, 0, 0, 0, 0],
  },
  {
    id: 5,
    name: 'NIKITYAO',
    games: 0,
    wins: 0,
    loses: 0,
    goalsScored: 0,
    goalsMissed: 0,

    lastGames: [0, 0, 0, 0, 0],
  },
  {
    id: 6,
    name: 'IVANYAO',
    games: 0,
    wins: 0,
    loses: 0,
    goalsScored: 0,
    goalsMissed: 0,
    lastGames: [0, 0, 0, 0, 0],
  },
];

export default players;
